#define REG(p) ((volatile uint32_t *)(p))

//                                                                            //
//                           GPIO registers                                   //
//                                                                            //

#define GPIO_DATA(p) REG(p + 0x000) // GPIO Data (p. 662)
#define GPIO_DIR(p) REG(p + 0x400) // GPIO Direction (p. 663)
#define GPIO_IS(p) REG(p + 0x404) // GPIO Interrupt Sense (p. 664)
#define GPIO_IBE(p) REG(p + 0x408) // GPIO Interrupt Both Edges (p. 665)
#define GPIO_IEV(p) REG(p + 0x40C) // GPIO Interrupt Event (p. 666)
#define GPIO_IM(p) REG(p + 0x410) // GPIO Interrupt Mask (p. 667)
#define GPIO_RIS(p) REG(p + 0x414) // GPIO Raw Interrupt Status (p. 668)
#define GPIO_MIS(p) REG(p + 0x418) // GPIO Masked Interrupt Status (p. 669)
#define GPIO_ICR(p) REG(p + 0x41C) // GPIO Interrupt Clear (p. 670)
#define GPIO_AFSEL(p) REG(p + 0x420) // GPIO Alternate Function Select (p. 671)
#define GPIO_DR2R(p) REG(p + 0x500) // GPIO 2-mA Drive Select (p. 673)
#define GPIO_DR4R(p) REG(p + 0x504) // GPIO 4-mA Drive Select (p. 674)
#define GPIO_DR8R(p) REG(p + 0x508) // GPIO 8-mA Drive Select (p. 675)
#define GPIO_ODR(p) REG(p + 0x50C) // GPIO Open Drain Select (p. 676)
#define GPIO_PUR(p) REG(p + 0x510) // GPIO Pull-Up Select (p. 677)
#define GPIO_PDR(p) REG(p + 0x514) // GPIO Pull-Down Select (p. 679)
#define GPIO_SLR(p) REG(p + 0x518) // GPIO Slew Rate Control Select (p. 681)
#define GPIO_DEN(p) REG(p + 0x51C) // GPIO Digital Enable (p. 682)
#define GPIO_LOCK(p) REG(p + 0x520) // GPIO Lock (p. 684)
#define GPIO_CR(p) REG(p + 0x524) // GPIO Commit (p. 685)
#define GPIO_AMSEL(p) REG(p + 0x528) // GPIO Analog Mode Select (p. 687)
#define GPIO_PCTL(p) REG(p + 0x52C) // GPIO Port Control (p. 688)
#define GPIO_ADCCTL(p) REG(p + 0x530) // GPIO ADC Control (p. 690)
#define GPIO_DMACTL(p) REG(p + 0x534) // GPIO DMA Control (p. 691)
#define GPIO_PeriphID4(p) REG(p + 0xFD0) // GPIO Peripheral Identification 4 (p. 692)
#define GPIO_PeriphID5(p) REG(p + 0xFD4) // GPIO Peripheral Identification 5 (p. 693)
#define GPIO_PeriphID6(p) REG(p + 0xFD8) // GPIO Peripheral Identification 6 (p. 694)
#define GPIO_PeriphID7(p) REG(p + 0xFDC) // GPIO Peripheral Identification 7 (p. 695)
#define GPIO_PeriphID0(p) REG(p + 0xFE0) // GPIO Peripheral Identification 0 (p. 696)
#define GPIO_PeriphID1(p) REG(p + 0xFE4) // GPIO Peripheral Identification 1 (p. 697)
#define GPIO_PeriphID2(p) REG(p + 0xFE8) // GPIO Peripheral Identification 2 (p. 698)
#define GPIO_PeriphID3(p) REG(p + 0xFEC) // GPIO Peripheral Identification 3 (p. 699)
#define GPIO_PCellID0(p) REG(p + 0xFF0) // GPIO PrimeCell Identification 0 (p. 700)
#define GPIO_PCellID1(p) REG(p + 0xFF4) // GPIO PrimeCell Identification 1 (p. 701)
#define GPIO_PCellID2(p) REG(p + 0xFF8) // GPIO PrimeCell Identification 2 (p. 702)
#define GPIO_PCellID3(p) REG(p + 0xFFC) // GPIO PrimeCell Identification 3 (p. 703)

//                                                                            //
//                              Timer registers
//                                                                            //

#define GPTM_CFG(p) REG(p + 0x000) // GPTM Configuration (p. 727)
#define GPTM_TAMR(p) REG(p + 0x004) // GPTM Timer A Mode (p. 729)
#define GPTM_TBMR(p) REG(p + 0x008) // GPTM Timer B Mode (p. 733)
#define GPTM_CTL(p) REG(p + 0x00C) // GPTM Control (p. 737)
#define GPTM_SYNC(p) REG(p + 0x010) // GPTM Synchronize (p. 741)
#define GPTM_IMR(p) REG(p + 0x018) // GPTM Interrupt Mask (p. 745)
#define GPTM_RIS(p) REG(p + 0x01C) // GPTM Raw Interrupt Status (p. 748)
#define GPTM_MIS(p) REG(p + 0x020) // GPTM Masked Interrupt Status (p. 751)
#define GPTM_ICR(p) REG(p + 0x024) // GPTM Interrupt Clear (p. 754)
#define GPTM_TAILR(p) REG(p + 0x028) // GPTM Timer A Interval Load (p. 756)
#define GPTM_TBILR(p) REG(p + 0x02C) // GPTM Timer B Interval Load (p. 757)
#define GPTM_TAMATCHR(p) REG(p + 0x030) // GPTM Timer A Match (p. 758)
#define GPTM_TBMATCHR(p) REG(p + 0x034) // GPTM Timer B Match (p. 759)
#define GPTM_TAPR(p) REG(p + 0x038) // GPTM Timer A Prescale (p. 760)
#define GPTM_TBPR(p) REG(p + 0x03C) // GPTM Timer B Prescale (p. 761)
#define GPTM_TAPMR(p) REG(p + 0x040) // GPTM TimerA Prescale Match (p. 762)
#define GPTM_TBPMR(p) REG(p + 0x044) // GPTM TimerB Prescale Match (p. 763)
#define GPTM_TAR(p) REG(p + 0x048) // GPTM Timer A (p. 764)
#define GPTM_TBR(p) REG(p + 0x04C) // GPTM Timer B (p. 765)
#define GPTM_TAV(p) REG(p + 0x050) // GPTM Timer A Value (p. 766)
#define GPTM_TBV(p) REG(p + 0x054) // GPTM Timer B Value (p. 767)
#define GPTM_RTCPD(p) REG(p + 0x058) // GPTM RTC Predivide (p. 768)
#define GPTM_TAPS(p) REG(p + 0x05C) // GPTM Timer A Prescale Snapshot (p. 769)
#define GPTM_TBPS(p) REG(p + 0x060) // GPTM Timer B Prescale Snapshot (p. 770)
#define GPTM_TAPV(p) REG(p + 0x064) // GPTM Timer A Prescale Value (p. 771)
#define GPTM_TBPV(p) REG(p + 0x068) // GPTM Timer B Prescale Value (p. 772)
#define GPTM_PP(p) REG(p + 0xFC0) // GPTM Peripheral Properties (p. 773)
