#define REG(p) ((volatile uint32_t *)(p))


//                                                                            //
//                              Sysctl registers                              //
//                                                                            //

#define SYSCTL_DID0(p) REG(p + 0x000) // Device Identification 0 (p. 238)
#define SYSCTL_DID1(p) REG(p + 0x004) // Device Identification 1 (p. 240)
#define SYSCTL_PBORCTL(p) REG(p + 0x030) // Brown-Out Reset Control (p. 243)
#define SYSCTL_RIS(p) REG(p + 0x050) // Raw Interrupt Status (p. 244)
#define SYSCTL_IMC(p) REG(p + 0x054) // Interrupt Mask Control (p. 247)
#define SYSCTL_1CMISC(p) REG(p + 0x058) // Masked Interrupt Status and Clear (p. 249)
#define SYSCTL_RESC(p) REG(p + 0x05C) // Reset Cause (p. 252)
#define SYSCTL_RCC(p) REG(p + 0x060) // Run-Mode Clock Configuration (p. 254)
#define SYSCTL_GPIOHBCTL(p) REG(p + 0x06C) // GPIO High-Performance Bus Control (p. 258)
#define SYSCTL_RCC2(p) REG(p + 0x070) // Run-Mode Clock Configuration 2 (p. 260)
#define SYSCTL_MOSCCTL(p) REG(p + 0x07C) // Main Oscillator Control (p. 263)
#define SYSCTL_DSLPCLKCFG(p) REG(p + 0x144) // Deep Sleep Clock Configuration (p. 264)
#define SYSCTL_SYSPROP(p) REG(p + 0x14C) // System Properties (p. 266)
#define SYSCTL_PIOSCCAL(p) REG(p + 0x150) // Precision Internal Oscillator Calibration (p. 268)
#define SYSCTL_PIOSCSTAT(p) REG(p + 0x154) // Precision Internal Oscillator Statistics (p. 270)
#define SYSCTL_PLLFREQ0(p) REG(p + 0x160) // PLL Frequency 0 (p. 271)
#define SYSCTL_PLLFREQ1(p) REG(p + 0x164) // PLL Frequency 1 (p. 272)
#define SYSCTL_PLLSTAT(p) REG(p + 0x168) // PLL Status (p. 273)
#define SYSCTL_SLPPWRCFG(p) REG(p + 0x188) // Sleep Power Configuration (p. 274)
#define SYSCTL_DSLPPWRCFG(p) REG(p + 0x18C) // Deep-Sleep Power Configuration (p. 276)
#define SYSCTL_LDOSPCTL(p) REG(p + 0x1B4) // LDO Sleep Power Control (p. 278)
#define SYSCTL_LDOSPCAL(p) REG(p + 0x1B8) // LDO Sleep Power Calibration (p. 280)
#define SYSCTL_LDODPCTL(p) REG(p + 0x1BC) // LDO Deep-Sleep Power Control (p. 281)
#define SYSCTL_LDODPCAL(p) REG(p + 0x1C0) // LDO Deep-Sleep Power Calibration (p. 283)
#define SYSCTL_SDPMST(p) REG(p + 0x1CC) // Sleep / Deep-Sleep Power Mode Status (p. 284)
#define SYSCTL_PPWD(p) REG(p + 0x300) // Watchdog Timer Peripheral Present (p. 287)
#define SYSCTL_PPTIMER(p) REG(p + 0x304) // 16/32-Bit General-Purpose Timer Peripheral Present (p. 288)
#define SYSCTL_PPGPIO(p) REG(p + 0x308) // General-Purpose Input/Output Peripheral Present (p. 290)
#define SYSCTL_PPDMA(p) REG(p + 0x30C) // Micro Direct Memory Access Peripheral Present (p. 293)
#define SYSCTL_PPHIB(p) REG(p + 0x314) // Hibernation Peripheral Present (p. 294)
#define SYSCTL_PPUART(p) REG(p + 0x318) // Universal Asynchronous Receiver/Transmitter Peripheral Present (p. 295)
#define SYSCTL_PPSSI(p) REG(p + 0x31C) // Synchronous Serial Interface Peripheral Present (p. 297)
#define SYSCTL_PPI2C(p) REG(p + 0x320) // Inter-Integrated Circuit Peripheral Present (p. 299)
#define SYSCTL_PPUSB(p) REG(p + 0x328) // Universal Serial Bus Peripheral Present (p. 301)
#define SYSCTL_PPCAN(p) REG(p + 0x334) // Controller Area Network Peripheral Present (p. 302)
#define SYSCTL_PPADC(p) REG(p + 0x338) // Analog-to-Digital Converter Peripheral Present (p. 303)
#define SYSCTL_PPACMP(p) REG(p + 0x33C) // Analog Comparator Peripheral Present (p. 304)
#define SYSCTL_PPPWM(p) REG(p + 0x340) // Pulse Width Modulator Peripheral Present (p. 305)
#define SYSCTL_PPQEI(p) REG(p + 0x344) // Quadrature Encoder Interface Peripheral Present (p. 306)
#define SYSCTL_PPEEPROM(p) REG(p + 0x358) // EEPROM Peripheral Present (p. 307)
#define SYSCTL_PPWTIMER(p) REG(p + 0x35C) // 32/64-Bit Wide General-Purpose Timer Peripheral Present (p. 308)
#define SYSCTL_SRWD(p) REG(p + 0x500) // Watchdog Timer Software Reset (p. 310)
#define SYSCTL_SRTIMER(p) REG(p + 0x504) // 16/32-Bit General-Purpose Timer Software Reset (p. 312)
#define SYSCTL_SRGPIO(p) REG(p + 0x508) // General-Purpose Input/Output Software Reset (p. 314)
#define SYSCTL_SRDMA(p) REG(p + 0x50C) // Micro Direct Memory Access Software Reset (p. 316)
#define SYSCTL_SRHIB(p) REG(p + 0x514) // Hibernation Software Reset (p. 317)
#define SYSCTL_SRUART(p) REG(p + 0x518) // Universal Asynchronous Receiver/Transmitter Software Reset (p. 318)
#define SYSCTL_SRSSI(p) REG(p + 0x51C) // Synchronous Serial Interface Software Reset (p. 320)
#define SYSCTL_SRI2C(p) REG(p + 0x520) // Inter-Integrated Circuit Software Reset (p. 322)
#define SYSCTL_SRUSB(p) REG(p + 0x528) // Universal Serial Bus Software Reset (p. 324)
#define SYSCTL_SRCAN(p) REG(p + 0x534) // Controller Area Network Software Reset (p. 325)
#define SYSCTL_SRADC(p) REG(p + 0x538) // Analog-to-Digital Converter Software Reset (p. 327)
#define SYSCTL_SRACMP(p) REG(p + 0x53C) // Analog Comparator Software Reset (p. 329)
#define SYSCTL_SRPWM(p) REG(p + 0x540) // Pulse Width Modulator Software Reset (p. 330)
#define SYSCTL_SRQEI(p) REG(p + 0x544) // Quadrature Encoder Interface Software Reset (p. 332)
#define SYSCTL_SREEPROM(p) REG(p + 0x558) // EEPROM Software Reset (p. 334)
#define SYSCTL_SRWTIMER(p) REG(p + 0x55C) // 32/64-Bit Wide General-Purpose Timer Software Reset (p. 335)
#define SYSCTL_RCGCWD(p) REG(p + 0x600) // Watchdog Timer Run Mode Clock Gating Control (p. 337)
#define SYSCTL_RCGCTIMER(p) REG(p + 0x604) // 16/32-Bit General-Purpose Timer Run Mode Clock Gating Control (p. 338)
#define SYSCTL_RCGCGPIO(p) REG(p + 0x608) // General-Purpose Input/Output Run Mode Clock Gating Control (p. 340)
#define SYSCTL_RCGCDMA(p) REG(p + 0x60C) // Micro Direct Memory Access Run Mode Clock Gating Control (p. 342)
#define SYSCTL_RCGCHIB(p) REG(p + 0x614) // Hibernation Run Mode Clock Gating Control (p. 343)
#define SYSCTL_RCGCUART(p) REG(p + 0x618) // Universal Asynchronous Receiver/Transmitter Run Mode Clock Gating Control (p. 344)
#define SYSCTL_RCGCSSI(p) REG(p + 0x61C) // Synchronous Serial Interface Run Mode Clock Gating Control (p. 346)
#define SYSCTL_RCGCI2C(p) REG(p + 0x620) // Inter-Integrated Circuit Run Mode Clock Gating Control (p. 348)
#define SYSCTL_RCGCUSB(p) REG(p + 0x628) // Universal Serial Bus Run Mode Clock Gating Control (p. 350)
#define SYSCTL_RCGCCAN(p) REG(p + 0x634) // Controller Area Network Run Mode Clock Gating Control (p. 351)
#define SYSCTL_RCGCADC(p) REG(p + 0x638) // Analog-to-Digital Converter Run Mode Clock Gating Control (p. 352)
#define SYSCTL_RCGCACMP(p) REG(p + 0x63C) // Analog Comparator Run Mode Clock Gating Control (p. 353)
#define SYSCTL_RCGCPWM(p) REG(p + 0x640) // Pulse Width Modulator Run Mode Clock Gating Control (p. 354)
#define SYSCTL_RCGCQEI(p) REG(p + 0x644) // Quadrature Encoder Interface Run Mode Clock Gating Control (p. 355)
#define SYSCTL_RCGCEEPROM(p) REG(p + 0x658) // EEPROM Run Mode Clock Gating Control (p. 356)
#define SYSCTL_RCGCWTIMER(p) REG(p + 0x65C) // 32/64-Bit Wide General-Purpose Timer Run Mode Clock Gating Control (p. 357)
#define SYSCTL_SCGCWD(p) REG(p + 0x700) // Watchdog Timer Sleep Mode Clock Gating Control (p. 359)
#define SYSCTL_SCGCTIMER(p) REG(p + 0x704) // 16/32-Bit General-Purpose Timer Sleep Mode Clock Gating Control (p. 360)
#define SYSCTL_SCGCGPIO(p) REG(p + 0x708) // General-Purpose Input/Output Sleep Mode Clock Gating Control (p. 362)
#define SYSCTL_SCGCDMA(p) REG(p + 0x70C) // Micro Direct Memory Access Sleep Mode Clock Gating Control (p. 364)
#define SYSCTL_SCGCHIB(p) REG(p + 0x714) // Hibernation Sleep Mode Clock Gating Control (p. 365)
#define SYSCTL_SCGCUART(p) REG(p + 0x718) // Universal Asynchronous Receiver/Transmitter Sleep Mode Clock Gating Control (p. 366)
#define SYSCTL_SCGCSSI(p) REG(p + 0x71C) // Synchronous Serial Interface Sleep Mode Clock Gating Control (p. 368)
#define SYSCTL_SCGCI2C(p) REG(p + 0x720) // Inter-Integrated Circuit Sleep Mode Clock Gating Control (p. 370)
#define SYSCTL_SCGCUSB(p) REG(p + 0x728) // Universal Serial Bus Sleep Mode Clock Gating Control (p. 372)
#define SYSCTL_SCGCCAN(p) REG(p + 0x734) // Controller Area Network Sleep Mode Clock Gating Control (p. 373)
#define SYSCTL_SCGCADC(p) REG(p + 0x738) // Analog-to-Digital Converter Sleep Mode Clock Gating Control (p. 374)
#define SYSCTL_SCGCACMP(p) REG(p + 0x73C) // Analog Comparator Sleep Mode Clock Gating Control (p. 375)
#define SYSCTL_SCGCPWM(p) REG(p + 0x740) // Pulse Width Modulator Sleep Mode Clock Gating Control (p. 376)
#define SYSCTL_SCGCQEI(p) REG(p + 0x744) // Quadrature Encoder Interface Sleep Mode Clock Gating Control (p. 377)
#define SYSCTL_SCGCEEPROM(p) REG(p + 0x758) // EEPROM Sleep Mode Clock Gating Control (p. 378)
#define SYSCTL_SCGCWTIMER(p) REG(p + 0x75C) // 32/64-Bit Wide General-Purpose Timer Sleep Mode Clock Gating Control (p. 379)
#define SYSCTL_DCGCWD(p) REG(p + 0x800) // Watchdog Timer Deep-Sleep Mode Clock Gating Control (p. 381)
#define SYSCTL_DCGCTIMER(p) REG(p + 0x804) // 16/32-Bit General-Purpose Timer Deep-Sleep Mode Clock Gating Control (p. 382)
#define SYSCTL_DCGCGPIO(p) REG(p + 0x808) // General-Purpose Input/Output Deep-Sleep Mode Clock Gating Control (p. 384)
#define SYSCTL_DCGCDMA(p) REG(p + 0x80C) // Micro Direct Memory Access Deep-Sleep Mode Clock Gating Control (p. 386)
#define SYSCTL_DCGCHIB(p) REG(p + 0x814) // Hibernation Deep-Sleep Mode Clock Gating Control (p. 387)
#define SYSCTL_DCGCUART(p) REG(p + 0x818) // Universal Asynchronous Receiver/Transmitter Deep-Sleep Mode Clock Gating Control (p. 388)
#define SYSCTL_DCGCSSI(p) REG(p + 0x81C) // Synchronous Serial Interface Deep-Sleep Mode Clock Gating Control (p. 390)
#define SYSCTL_DCGCI2C(p) REG(p + 0x820) // Inter-Integrated Circuit Deep-Sleep Mode Clock Gating Control (p. 392)
#define SYSCTL_DCGCUSB(p) REG(p + 0x828) // Universal Serial Bus Deep-Sleep Mode Clock Gating Control (p. 394)
#define SYSCTL_DCGCCAN(p) REG(p + 0x834) // Controller Area Network Deep-Sleep Mode Clock Gating Control (p. 395)
#define SYSCTL_DCGCADC(p) REG(p + 0x838) // Analog-to-Digital Converter Deep-Sleep Mode Clock Gating Control (p. 396)
#define SYSCTL_DCGCACMP(p) REG(p + 0x83C) // Analog Comparator Deep-Sleep Mode Clock Gating Control (p. 397)
#define SYSCTL_DCGCPWM(p) REG(p + 0x840) // Pulse Width Modulator Deep-Sleep Mode Clock Gating Control (p. 398)
#define SYSCTL_DCGCQEI(p) REG(p + 0x844) // Quadrature Encoder Interface Deep-Sleep Mode Clock Gating Control (p. 399)
#define SYSCTL_DCGCEEPROM(p) REG(p + 0x858) // EEPROM Deep-Sleep Mode Clock Gating Control (p. 400)
#define SYSCTL_DCGCWTIMER(p) REG(p + 0x85C) // 32/64-Bit Wide General-Purpose Timer Deep-Sleep Mode Clock Gating Control (p. 401)
#define SYSCTL_PRWD(p) REG(p + 0xA00) // Watchdog Timer Peripheral Ready (p. 403)
#define SYSCTL_PRTIMER(p) REG(p + 0xA04) // 16/32-Bit General-Purpose Timer Peripheral Ready (p. 404)
#define SYSCTL_PRGPIO(p) REG(p + 0xA08) // General-Purpose Input/Output Peripheral Ready (p. 406)
#define SYSCTL_PRDMA(p) REG(p + 0xA0C) // Micro Direct Memory Access Peripheral Ready (p. 408)
#define SYSCTL_PRHIB(p) REG(p + 0xA14) // Hibernation Peripheral Ready (p. 409)
#define SYSCTL_PRUART(p) REG(p + 0xA18) // Universal Asynchronous Receiver/Transmitter Peripheral Ready (p. 410)
#define SYSCTL_PRSSI(p) REG(p + 0xA1C) // Synchronous Serial Interface Peripheral Ready (p. 412)
#define SYSCTL_PRI2C(p) REG(p + 0xA20) // Inter-Integrated Circuit Peripheral Ready (p. 414)
#define SYSCTL_PRUSB(p) REG(p + 0xA28) // Universal Serial Bus Peripheral Ready (p. 416)
#define SYSCTL_PRCAN(p) REG(p + 0xA34) // Controller Area Network Peripheral Ready (p. 417)
#define SYSCTL_PRADC(p) REG(p + 0xA38) // Analog-to-Digital Converter Peripheral Ready (p. 418)
#define SYSCTL_PRACMP(p) REG(p + 0xA3C) // Analog Comparator Peripheral Ready (p. 419)
#define SYSCTL_PRPWM(p) REG(p + 0xA40) // Pulse Width Modulator Peripheral Ready (p. 420)
#define SYSCTL_PRQEI(p) REG(p + 0xA44) // Quadrature Encoder Interface Peripheral Ready (p. 421)
#define SYSCTL_PREEPROM(p) REG(p + 0xA58) // EEPROM Peripheral Ready (p. 422)
#define SYSCTL_PRWTIMER(p) REG(p + 0xA5C) // 32/64-Bit Wide General-Purpose Timer Peripheral Ready (p. 423)

//                                                                            //
//                           GPIO registers                                   //
//                                                                            //

#define GPIO_DATA(p) REG(p + 0x000) // GPIO Data (p. 662)
#define GPIO_DIR(p) REG(p + 0x400) // GPIO Direction (p. 663)
#define GPIO_IS(p) REG(p + 0x404) // GPIO Interrupt Sense (p. 664)
#define GPIO_IBE(p) REG(p + 0x408) // GPIO Interrupt Both Edges (p. 665)
#define GPIO_IEV(p) REG(p + 0x40C) // GPIO Interrupt Event (p. 666)
#define GPIO_IM(p) REG(p + 0x410) // GPIO Interrupt Mask (p. 667)
#define GPIO_RIS(p) REG(p + 0x414) // GPIO Raw Interrupt Status (p. 668)
#define GPIO_MIS(p) REG(p + 0x418) // GPIO Masked Interrupt Status (p. 669)
#define GPIO_ICR(p) REG(p + 0x41C) // GPIO Interrupt Clear (p. 670)
#define GPIO_AFSEL(p) REG(p + 0x420) // GPIO Alternate Function Select (p. 671)
#define GPIO_DR2R(p) REG(p + 0x500) // GPIO 2-mA Drive Select (p. 673)
#define GPIO_DR4R(p) REG(p + 0x504) // GPIO 4-mA Drive Select (p. 674)
#define GPIO_DR8R(p) REG(p + 0x508) // GPIO 8-mA Drive Select (p. 675)
#define GPIO_ODR(p) REG(p + 0x50C) // GPIO Open Drain Select (p. 676)
#define GPIO_PUR(p) REG(p + 0x510) // GPIO Pull-Up Select (p. 677)
#define GPIO_PDR(p) REG(p + 0x514) // GPIO Pull-Down Select (p. 679)
#define GPIO_SLR(p) REG(p + 0x518) // GPIO Slew Rate Control Select (p. 681)
#define GPIO_DEN(p) REG(p + 0x51C) // GPIO Digital Enable (p. 682)
#define GPIO_LOCK(p) REG(p + 0x520) // GPIO Lock (p. 684)
#define GPIO_CR(p) REG(p + 0x524) // GPIO Commit (p. 685)
#define GPIO_AMSEL(p) REG(p + 0x528) // GPIO Analog Mode Select (p. 687)
#define GPIO_PCTL(p) REG(p + 0x52C) // GPIO Port Control (p. 688)
#define GPIO_ADCCTL(p) REG(p + 0x530) // GPIO ADC Control (p. 690)
#define GPIO_DMACTL(p) REG(p + 0x534) // GPIO DMA Control (p. 691)
#define GPIO_PeriphID4(p) REG(p + 0xFD0) // GPIO Peripheral Identification 4 (p. 692)
#define GPIO_PeriphID5(p) REG(p + 0xFD4) // GPIO Peripheral Identification 5 (p. 693)
#define GPIO_PeriphID6(p) REG(p + 0xFD8) // GPIO Peripheral Identification 6 (p. 694)
#define GPIO_PeriphID7(p) REG(p + 0xFDC) // GPIO Peripheral Identification 7 (p. 695)
#define GPIO_PeriphID0(p) REG(p + 0xFE0) // GPIO Peripheral Identification 0 (p. 696)
#define GPIO_PeriphID1(p) REG(p + 0xFE4) // GPIO Peripheral Identification 1 (p. 697)
#define GPIO_PeriphID2(p) REG(p + 0xFE8) // GPIO Peripheral Identification 2 (p. 698)
#define GPIO_PeriphID3(p) REG(p + 0xFEC) // GPIO Peripheral Identification 3 (p. 699)
#define GPIO_PCellID0(p) REG(p + 0xFF0) // GPIO PrimeCell Identification 0 (p. 700)
#define GPIO_PCellID1(p) REG(p + 0xFF4) // GPIO PrimeCell Identification 1 (p. 701)
#define GPIO_PCellID2(p) REG(p + 0xFF8) // GPIO PrimeCell Identification 2 (p. 702)
#define GPIO_PCellID3(p) REG(p + 0xFFC) // GPIO PrimeCell Identification 3 (p. 703)

//                                                                            //
//                              Timer registers                               //
//                                                                            //

#define GPTM_CFG(p) REG(p + 0x000) // GPTM Configuration (p. 727)
#define GPTM_TAMR(p) REG(p + 0x004) // GPTM Timer A Mode (p. 729)
#define GPTM_TBMR(p) REG(p + 0x008) // GPTM Timer B Mode (p. 733)
#define GPTM_CTL(p) REG(p + 0x00C) // GPTM Control (p. 737)
#define GPTM_SYNC(p) REG(p + 0x010) // GPTM Synchronize (p. 741)
#define GPTM_IMR(p) REG(p + 0x018) // GPTM Interrupt Mask (p. 745)
#define GPTM_RIS(p) REG(p + 0x01C) // GPTM Raw Interrupt Status (p. 748)
#define GPTM_MIS(p) REG(p + 0x020) // GPTM Masked Interrupt Status (p. 751)
#define GPTM_ICR(p) REG(p + 0x024) // GPTM Interrupt Clear (p. 754)
#define GPTM_TAILR(p) REG(p + 0x028) // GPTM Timer A Interval Load (p. 756)
#define GPTM_TBILR(p) REG(p + 0x02C) // GPTM Timer B Interval Load (p. 757)
#define GPTM_TAMATCHR(p) REG(p + 0x030) // GPTM Timer A Match (p. 758)
#define GPTM_TBMATCHR(p) REG(p + 0x034) // GPTM Timer B Match (p. 759)
#define GPTM_TAPR(p) REG(p + 0x038) // GPTM Timer A Prescale (p. 760)
#define GPTM_TBPR(p) REG(p + 0x03C) // GPTM Timer B Prescale (p. 761)
#define GPTM_TAPMR(p) REG(p + 0x040) // GPTM TimerA Prescale Match (p. 762)
#define GPTM_TBPMR(p) REG(p + 0x044) // GPTM TimerB Prescale Match (p. 763)
#define GPTM_TAR(p) REG(p + 0x048) // GPTM Timer A (p. 764)
#define GPTM_TBR(p) REG(p + 0x04C) // GPTM Timer B (p. 765)
#define GPTM_TAV(p) REG(p + 0x050) // GPTM Timer A Value (p. 766)
#define GPTM_TBV(p) REG(p + 0x054) // GPTM Timer B Value (p. 767)
#define GPTM_RTCPD(p) REG(p + 0x058) // GPTM RTC Predivide (p. 768)
#define GPTM_TAPS(p) REG(p + 0x05C) // GPTM Timer A Prescale Snapshot (p. 769)
#define GPTM_TBPS(p) REG(p + 0x060) // GPTM Timer B Prescale Snapshot (p. 770)
#define GPTM_TAPV(p) REG(p + 0x064) // GPTM Timer A Prescale Value (p. 771)
#define GPTM_TBPV(p) REG(p + 0x068) // GPTM Timer B Prescale Value (p. 772)
#define GPTM_PP(p) REG(p + 0xFC0) // GPTM Peripheral Properties (p. 773)

